Algoritmo "4"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
//
Var
// Seção de Declarações das variáveis 
cont,nu:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont<-1
enquanto (cont <= 100) faca
       nu<-nu + cont
       cont<-cont + 1
fimenquanto
           escreval("a soma ods primeiros 100 numeros:",nu)
Fimalgoritmo