Algoritmo "08"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/11/2023
Var
// Seção de Declarações das variáveis 
cont,acu:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
acu<- 0
para cont de 3 ate 21 passo 1 faca
se (cont mod 2 = 0)entao
acu<- acu+cont
fimse
fimpara
escreval(acu)

Fimalgoritmo